name: Merge JSON PullRequest Check

on:
  pull_request:
    paths:
      - Lua/**

jobs:
  merge-json-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install jsonmerge

    - name: Merge JSON files Check
      run: |
        python luatranslationmerger.py
